default: &default
  region: ap-northeast-1
  vpc_id: vpc-4c6f2825
  subnet_id: subnet-456f282c # ap-northeast-1b

ec2_default: &ec2_default
  <<: *default
  image_id: ami-4985b048 # Amazon Linux AMI 2014.09.1 (HVM)
  security_group_ids:
    - sg-d65d42ba # default
    - sg-1454ac71 # ssh-login
  key_name: "mikeda"
  hosted_zone_id: Z3J5MVVWBVNX6B # mikeda.jp
  iam_instance_profile: "default"
  ebs_size: 30
